title: "Nelson Tate"
author: "Nelson Tate"
description: "Georgia Institute of Technology"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Home"}
  - {url: Nelson-Tate-CV.pdf, title: "CV"}
  - {file: "work.md", title: "Work"}
  - {file: "projects.md", title: "Projects"}
  - {file: "skills.md", title: "Skills"}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "nelsontate2021@gmail.com"}
  - {title: Github, icon: github, url: "https://nelsonbtate.github.io/"}
  - {title: LinkedIn, icon: rss, url: "https://www.linkedin.com/in/nelsontate/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
